name: Scrape Okta Status and Commit JSON

on:
  schedule:
    - cron: '*/15 * * * *'  # cada 30 minutos
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar scraper y subir JSON
        run: npm start

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/oktaStatus.json
          git commit -m "update: oktaStatus.json [auto]" || echo "No changes to commit"
          git push