name: Scrape Okta Status

on:
  schedule:
    - cron: '*/30 * * * *'  # cada 30 minutos
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar scraper y subir JSON
        run: npm start
        env:
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
